import Head from "next/head";
import { Image } from "@unpic/react/nextjs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          src="https://images.unsplash.com/photo-1617718295766-0f839c2853e7"
          layout="fullWidth"
          alt="fullWidth"
          aspectRatio={16 / 9}
          priority
        />
        <Image
          src="https://cdn.shopify.com/static/sample-images/garnished.jpeg"
          layout="constrained"
          width={800}
          height={600}
          alt="constrained"
        />
        <Image
          src="https://bunnyoptimizerdemo.b-cdn.net/bunny7.jpg"
          width={800}
          height={600}
          layout="fixed"
          alt="fixed"
          operations={{
            bunny: {
              flop: true,
            },
          }}
        />
        <div style={{ height: 10000 }}></div>
        <Image
          src="https://cdn.shopify.com/static/sample-images/bath.jpeg"
          layout="constrained"
          width={600}
          height={800}
          alt="offscreen"
        />
      </div>
    </>
  );
}
